var data = {

	introText: "<p>Grams likes to talk about how the world used to be, with running water and cars and airplanes and all that.  That's not the world you ever knew.</p><p>You live in a little town huddling in the midst of a wasteland.  There's never enough of what's needed, and usually too much of what's not.  There are a few scraggely roads towards the horizon that nobody ever takes.</p><p>You figure: there's other towns out there.  They must need things, and have things, and maybe if somebody travels the road, they could help meet those needs.  Maybe things could get better.</p><p>You've got a donkey cart.  Your friend says they'll join you to see what's out there.</p><p>What will you find Down the Phoenix Road?</p>",

	commodities: {
	
		food: {
			name: 'Food',
			common: true,
			baseValue: 15,
			stability: 6,
			cargo: true,
			icon: 'cutlery',
			iconColor: 'grey',
		},
		
		water: {
			name: 'Water',
			common: true,
			baseValue: 10,
			stability: 3,
			cargo: true,
			icon: 'tint',
			iconColor: 'blue',
		},
		
		lumber: {
			name: 'Lumber',
			common: true,
			baseValue: 30,
			stability: 4,
			cargo: true,
			icon: 'tree',
			iconColor: 'green',
		},
		
		stone: {
			name: 'Stone',
			common: true,
			baseValue: 40,
			stability: 5,
			cargo: true,
			icon: 'institution',
			iconColor: 'darkgrey',
			},
		
		clothing: {
			name: 'Clothing',
			common: true,
			baseValue: 70,
			stability: 2,
			cargo: true,
			icon: 'black-tie',
		},
		
		tack: {
			name: 'Saddles & Tack',
			common: true,
			baseValue: 80,
			stability: 3,
			cargo: true,
			icon: 'link',
			iconColor: 'saddlebrown',
		},
		
		fuel: {
			name: 'Fuel',
			common: false,
			baseValue: 100,
			stability: 2,
			cargo: true,
			icon: 'tint',
			iconColor: 'olive',
		},
		
		fiber: {
			name: 'Fiber',
			common: false,
			baseValue: 20,
			stability: 3,
			cargo: true,
			icon: 'pagelines',
			iconColor: 'gold',
		},
		
		hides: {
			name: 'Hides',
			common: false,
			baseValue: 30,
			stability: 4,
			cargo: true,
			icon: 'joomla',
			iconColor: 'saddlebrown',
		},
		
		ore: {
			name: 'Ore',
			common: false,
			baseValue: 40,
			stability: 6,
			cargo: true,
			icon: 'cloud',
			iconColor: 'grey',
		},
		
		furniture: {
			name: 'Furniture',
			common: false,
			baseValue: 100,
			stability: 6,
			cargo: true,
			icon: 'bed',
			iconColor: 'saddlebrown',
		},
		
		leather: {
			name: 'Leather',
			common: false,
			baseValue: 50,
			stability: 2,
			cargo: true,
			icon: 'ticket',
			iconColor: 'saddlebrown',
		},
		
		crudeOil: {
			name: 'Crude Oil',
			common: false,
			baseValue: 50,
			stability: 3,
			cargo: true,
			icon: 'tint',
		},
		
		cloth: {
			name: 'Cloth',
			common: false,
			baseValue: 60,
			stability: 3,
			cargo: true,
			icon: 'map',
			iconColor: 'cyan',
		},
		
		metals: {
			name: 'Metals',
			common: false,
			baseValue: 100,
			stability: 4,
			cargo: true,
			icon: 'steam',
			iconColor: 'grey',
		},
		
		mail: {
			name: 'Mail',
			common: false,
			baseValue: 30,
			stability: 100,
			cargo: false,
			icon: 'envelope-o',
		},
		
		scrip: {
			name: 'Scrip',
			common: false,
			baseValue: 100,
			stability: 10,
			cargo: false,
			icon: 'bookmark',
			iconColor: 'peru',
		},
		
		passengers: {
			name: 'Passengers',
			common: false,
			baseValue: 0,
			stability: 0,
			cargo: true,
			icon: 'users'
		},
		
		child: {
			name: 'Child',
			common: false,
			baseValue: 0,
			stability: 0,
			cargo: false,
			icon: 'child'
		},
		
	},
	
	foraging: [
		"Townie",
		"Novice Camper",
		"Forager",
		"Hunter",
		"Outdoor Veteran",
		"Scavenger",
		"Hinterlander",
		"Wildling",
		"Survivalist",
		"Ranger",
	],
	
	selfDefense: [
		'green',
		'inexperienced',
		'hardened',
		'veteran',
		'elite',
		'badass',
		'not-to-be-fucked-with'
	],
	
	vision: [
		"naked eye",
		"Simple Spyglass",
		"Sextant",
		"Binoculars",
		"Porro Prism Binoculars",
		"Refracting Telescope",
		"Theodolite",
		"Reflecting Telescope",
		"Transit Theodolite",
		"Catadioptric Telescope",
		"Electro-optical Theodolite"
	],
	
	infrastructure: {
	
		kidOnABike: {
			name: 'Kid on a Bike',
			unitName: 'Kid on a Bike',
			recruit: 'bicycle',
			recruitCost: {},
			text: "There's a kid here with an ancient but functional bike.",
			passage: "There's a kid here with an ancient but functional bicycle.",
			spawn: "A kid finds an ancient but functional bicycle.",
			visible: false,
			initial: 'K',
		},
		nakedDowser:  {
			name: 'Naked Dowser',
			unitName: 'Clothed Dowser',
			recruit: 'dowser',
			recruitCost: {clothing:1,lumber:1},
			text: "This unfortunate dowser is huddled over a pitiful fire... naked.",
			passage: "Just outside of town, you come across a small cart with 'Dowsing Services' painted on the side.  In the shelter afforded by the cart sputters a pitiful fire, and beside the fire, shivering and cursing, is what you assume to be the dowser... naked as a jaybird.<p>At your hesitant inquiry, the dowser warns, 'Careful, the people in that town over yonder don't take kindly to bad news.  They left me like this when I couldn't find a spring some ancient fool swears he used to drink from as a kid.'<p>Whether or not you trade with the town, you wonder if there's anything you can do for the poor dowser.",
			spawn: "A travelling dowser runs afoul of the locals.",
			visible: false,
			initial: 'D',
		},
		tinkerCamp: {
			name: 'Tinker Camp',
			unitName: 'Tinker Band',
			recruit: 'tinkersCart',
			recruitCost: {food:8},
			text: "These tinkers are interested in work but skeptical of your ability to feed them.",
			passage: "This small band of tinkers travels town to town doing odd jobs.  When informed of your plans, they suggest they could help in exchange for regular meals.",
			spawn: "A band of tinkers arrives, offering to do odd jobs around town.",
			visible: false,
			initial: 'T',
		},
		burntOutBus: {
			name: 'Burnt Out Bus',
			unitName: 'Charred Bus',
			recruit: 'bus',
			recruitCost: {water:2,fuel:1,metals:1},
			text: "This burnt-out husk can be refurbished with a few materials.",
			passage: "You come across a burned-out vehicle, apparently hit by bandits.  It appears it was large enough for its former owners to live in... and die in.  They sure aren't using it anymore...",
			spawn: "A pyre of flames lights on the outskirts of town. After shouts, gunfire, and screams, the conflagration burns all night.",
			visible: false,
			initial: 'B',
		},
		cartwright: {
			name:'Cartwright',
			buildCost: {lumber:2},
			buildTime: 14,
			goodwill: 1,
			visible: false,
			buildUnits: [
				'donkeyCart',
				'oxCart',
				'horseCart',
				'tinkersCart',
				'dowser'
				],
			inputs: ['tack','lumber','fiber'],
			jobs: 4,
			initial: 'C',
		},
		hangar: {
			name:'Hangar',
			passage: "You come across a huge, old-world building, like half a barrel lying on its side... if that barrel was broader than any tree.  A handful of people mill about outside the structure, working diligently on repairing or building bits of machinery.  Inside... inside is a huge skeleton of metal beams draped in shimmering cloth.<p>At your approach, one of the workers waves a hand in welcome.  'Ah, the trader,' she shouts merrily.  'We've heard about you.  How'd you like to make your deliveries from the sky?'",
			spawn: "A group of road-weary travelers sets up shop in a cavernous old world ruin.",
			visible: true,
			buildUnits: ['zeppelin'],
			inputs: ['metals','fiber','fuel'],
			jobs: 15,
			initial: 'H',
		},
		arena: {
			name: 'Arena',
			passage: "This town hosts a no-holds-barred pit fighting event few days.  Road warriors, brutes, and soldiers from all over travel here to test their skills against each other. Admission can be pretty exclusive, especially for the best fighters' bouts, but there's also an amateur's night.  There are no rules inside the arena, which makes it a whole lot like fights you've seen out on the road.  Maybe you can learn a thing or two watching.",
			text: "Take in a bout at the arena, maybe you'll learn some tricks you can share with the other drivers.",
			spawn: "For lack of other entertainment, the locals put together a brutal pit-fighting arena.",
			visible: false,
			upgrade: 'selfDefense',
			upgradeDisplay: "Self Defense",
			jobs: 30,
			defense: 2,
			initial: 'A',
		},
		lensmeister: {
			name: 'Lensmeister',
			passage: "One of this town's eldest citizens has amassed a sizeable collection of ancient glass lenses.  Some of the pieces in the collection include spyglasses and powerful telescopes.  The elder is happy enough to gift you with a weak specimen in exchange for an evening of your stories.  They intimate that they'd be willing to part with even more powerful artifacts if you help their town.",
			text: "The elder is happy to share their collection of lenses with people who help the town.",
			spawn: "One of the elders here has started showing off their collection of old world lenses.",
			visible: false,
			upgrade: 'vision',
			upgradeDisplay: "Vision",
			jobs: 1,
			initial: 'L',
		},
		mechanic: {
			name:'Mechanic',
			passage: "This town is the home of an expert in ancient machines, a mechanic.  Cars and trucks resurrected from her junkyard are used throughout the town.  These powerful machines can haul more, and faster, than anything pulled by an animal.  For the right materials, she can rebuild one of the hulks in her junkyard for your use.",
			spawn: "A clattering, popping machine pulls up the road into town and disgorges a oil-stained mechanic.  She asks around town if there is a place she can set up shop.",
			visible: false,
			buildUnits: [
				'bicycle',
				'buggy',
				'wagon',
				'truck',
				'bus',
				'semi',
				'constructionCrew'
				],
			inputs: ['fuel','metals'],
			jobs: 8,
			initial: 'M',
		},
		naturalist: {
			name: 'Naturalist',
			passage: "One of this town's residents is a scientist, of sorts, studying the 'natural environment' of the wasteland.  They've collected copious notes on how the wasteland has changed from its former lush glory.  Some of those notes could help your drivers survive off the land when the going got tough.",
			text: "The naturalist will take a break from compiling their notes to share information about the wasteland... for a price.",
			spawn: "A dusty figure claws their way into the town, dragging a pack crammed full of notes about the wasteland's dangers… and its hidden resources.",
			visible: false,
			upgrade: 'foraging',
			upgradeDisplay: "Foraging",
			jobs: 1,
			initial: 'N',
		},
		refugeeFamily: {
			name: "Refugee Family",
			passage: "Just outside town is the tattered encampment of a small family of refugees.  They haven't asked to settle here, the locals say.  The family is determined to find their youngest member, who has been lost somewhere in the wasteland.",
			text: "This small family of refugees had to leave their home and now wanders the wasteland, searching for what they've lost.",
			spawn: "A small family of refugees makes their slow way up the road and sets up a temporary camp just outside town.  They don't settle; they seem to be looking for something special.",
			visible: false,
			turnIn: ['child'],
			buttonLabel: 'Reunite Family',
			onTurnIn: 'refugeeReunion',
			initial: 'R',
		},
		

		aqueduct: {
			name: 'Aqueduct',
			buildCost: {stone:4,lumber:2},
			requiredResource: ['river','spring'],
			buildTime: 42,
			replaces: ['well'],
			goodwill:2,
			visible: true,
			outputs: ['water'],
			provides: ['fire suppression'],
			jobs: 10,
		},
// 		bank: {
// 			name:'Bank',
// 			buildCost: {stone:4,lumber:2},
// 			buildTime: 14,
// 			goodwill: -10,
// 			visible: false,
// 			inputs: ['scrip'],
// 			outputs: ['scrip'],
// 			jobs: 10,
// 		},
		barracks: {
			name:'Barracks',
			buildCost: {stone:4,lumber:2,furniture:2},
			buildTime: 14,
			goodwill: 3,
			visible: true,
			inputs: ['fuel','clothing','furniture'],
			housing:100,
			jobs: 10,
		},
		bunker: {
			name:'Bunker',
			suffices: [' Bunker',' Hold'],
			buildCost: {stone:2,lumber:1},
			buildTime: 6,
			goodwill: 1,
			visible: false,
			inputs: ['fuel','furniture'],
			housing:20,
			defense:2,
			jobs: 1,
		},
		canals: {
			name: 'Canal System',
			buildCost: {stone:10,lumber:5},
			requiredResource: ['river'],
			buildTime: 56,
			goodwill: 1,
			visible: true,
			outputs: ['water','food'],
			provides: ['flood control','fire suppression'],
			jobs: 10,
		},
		carpenter: {
			name: 'Carpentry Shop',
			buildCost: {lumber:5,fiber:3},
			buildTime: 10,
			goodwill: 4,
			visible: false,
			inputs: ['lumber'],
			outputs: ['furniture'],
			jobs: 4,
		},
		cisterns: {
			name: 'Cisterns',
			buildCost: {stone:4},
			buildTime: 14,
			goodwill: 1,
			visible: true,
			outputs: ['water'],
			provides: ['fire suppression'],
			jobs: 2,
		},
		corral: {
			name: 'Corral',
			suffices: [' Ranch'],
			buildCost: {lumber:2,fiber:2},
			requiredResource: ['pasture'],
			buildTime: 6,
			goodwill: 2,
			visible: false,
			outputs: ['food','hides'],
			jobs: 10,
		},
		fields: {
			name: 'Fields',
			suffices: ['feld',' Farm'],
			buildCost: {lumber:1,fiber:4},
			requiredResource: ['river','spring'],
			buildTime: 14,
			goodwill: 1,
			visible: true,
			inputs: ['water'],
			outputs: ['food','fiber'],
			jobs: 50,
		},
		fireStation: {
			name: "Fire Station",
			buildCost: {lumber:8,furniture:2},
			buildTime:14,
			goodwill:3,
			visible: false,
			provides: ['fire suppression'],
			jobs: 10,
		},
		foundry: {
			name:'Foundry',
			suffices: [' Stacks'],
			buildCost: {stone:6,lumber:6,cloth:2,ore:5},
			buildTime: 20,
			goodwill: 5,
			visible: true,
			inputs: ['ore','fuel','water'],
			outputs: ['metals'],
			jobs: 20,
		},
		fortress: {
			name:'Fortress',
			suffices: [' Fort',' Castle','castle'],
			buildCost: {stone:8,lumber:8,fiber:2,cloth:2},
			buildTime: 56,
			replaces: ['bunker'],
			goodwill: 5,
			visible: true,
			inputs: ['fuel'],
			defense:5,
			jobs: 10,
		},
		granary: {
			name: 'Granaries',
			buildCost: {stone: 4,lumber:2},
			buildTime: 14,
			goodwill: 1,
			visible: true,
			jobs: 4,
			outputs: ['food'],
		},
		hovels: {
			name: 'Hovels & Shacks',
			suffices: [' Hole'],
			visible: false,
			inputs: ['furniture'],
			housing: 4,
		},
		loom: {
			name: 'Loom',
			buildCost: {lumber:2,fiber:4},
			buildTime: 8,
			goodwill: 3,
			visible: false,
			inputs: ['fiber'],
			outputs: ['cloth'],
			jobs: 10,
		},
		lumbermill: {
			name: 'Lumbermill',
			suffices: [' Mill'],
			buildCost: {lumber:3,fiber:2},
			requiredResource: ['forest'],
			buildTime: 14,
			goodwill:2,
			visible:false,
			inputs: ['metals'],
			outputs: ['lumber'],
			jobs: 50,
		},
		manorHouse: {
			name:'Manor House',
			suffices: [' Manse',' House',' Manor',' Plantation'],
			buildCost: {stone:2,lumber:2,cloth:2,furniture:4},
			buildTime: 28,
			goodwill: -1,
			visible: false,
			inputs: ['furniture'],
			housing:20,
			jobs: 5,
		},
		mineshaft: {
			name: 'Mineshaft',
			buildCost: {lumber:4,metals:2,stone:2},
			requiredResource: ['mineralVein'],
			buildTime: 28,
			replaces: ['openPitMine'],
			goodwill: 4,
			visible: false,
			inputs: ['fuel'],
			outputs: ['ore','stone'],
			jobs: 100,
		},
		oilWell: {
			name: 'Oil Well',
			suffices: [' Wells'],
			buildCost: {metals:8},
			requiredResource: ['oilReservoir'],
			buildTime: 14,
			goodwill: 3,
			visible: true,
			outputs: ['crudeOil'],
			inputs: ['metals'],
			jobs: 30,
		},
		orchards: {
			name: 'Orchards',
			suffices: [' Stand',' Arbors'],
			buildCost: {lumber:1},
			requiredResource: ['forest'],
			buildTime: 14,
			goodwill: 1,
			visible: true,
			inputs: ['water'],
			outputs: ['food'],
			jobs: 50,
		},
		openPitMine: {
			name: 'Open Pit Mine',
			suffices: [' Mine',' Hole',' Ditch',' Pit'],
			buildCost: {lumber:4},
			requiredResource: ['mineralVein'],
			buildTime: 21,
			goodwill: 2,
			visible: false,
			inputs: ['fuel'],
			outputs: ['ore','stone'],
			jobs: 50,
		},
// 		postOffice: {
// 			name: 'Post Office',
// 			buildCost: {lumber:1,stone:1},
// 			buildTime: 8,
// 			goodwill: 1,
// 			visible: false,
// 			outputs: ['mail'],
// 			jobs: 2,
// 		},
		quarry: {
			name: 'Quarry',
			suffices: [' Hole',' Ditch',' Pit'],
			buildCost: {lumber:4},
			requiredResource: ['outcropping'],
			buildTime: 14,
			goodwill: 2,
			visible: false,
			inputs: ['fuel'],
			outputs: ['stone'],
			jobs: 50,
		},
		refinery: {
			name: 'Refinery',
			suffices: [' Stacks',' Torch',' Station',' Tanks'],
			buildCost: {metals:3,crudeOil:5},
			buildTime: 28,
			goodwill: 5,
			visible: true,
			inputs: ['crudeOil','metals'],
			outputs: ['fuel'],
			jobs: 25,
		},
		reservoir: {
			name: "Reservoir",
			buildCost: {stone:6,lumber:4},
			buildTime:48,
			goodwill: 10,
			visible: true,
			outputs: ['water'],
			jobs: 2,
		},
		rowhouses: {
			name: 'Rowhouses',
			buildCost: {stone:4, lumber:2, cloth:2, furniture:2},
			buildTime: 14,
			goodwill: 3,
			replaces: ['hovels'],
			inputs: ['fuel','clothing','furniture'],
			visible: false,
			housing: 100,
		},
		saddler: {
			name: 'Saddler',
			buildCost: {lumber:1,fiber:3,leather:3},
			buildTime: 8,
			goodwill: 2,
			visible: false,
			inputs: ['leather'],
			outputs: ['tack'],
			jobs: 4,
		},
		scrapyard: {
			name: 'Scrapyard',
			buildCost: {lumber:2,stone:2},
			requiredResource: ['ruins'],
			buildTime: 21,
			visible: true,
			jobs: 4,
			potentialCommodities: ['cloth','clothing','fuel','metals','stone'],
			text: 'Sponsor local efforts to dig up something interesting. ',
			initial: 'S',
		},
		seine: {
			name: 'Seine',
			buildCost: {fiber:4},
			requiredResource: ['river'],
			buildTime: 2,
			goodwill: 1,
			visible: false,
			outputs: ['food'],
			jobs: 10,
		},
		seamstress: {
			name: 'Seamstress',
			buildCost: {lumber:1,fiber:1,leather:1,cloth:5},
			buildTime: 8,
			goodwill: 2,
			visible: false,
			inputs: ['cloth','leather'],
			outputs: ['clothing'],
			jobs: 6,
		},
		shantyTown: {
			name:'Shanty Town',
			buildCost: {stone:4,lumber:2,cloth:1},
			requiredResource: ['ruins'],
			buildTime: 42,
			replaces: ['hovels'],
			goodwill: 4,
			visible: false,
			inputs: ['fuel','clothing','furniture'],
			housing:150,
			jobs: 10,
		},
		stoneWall: {
			name:'Stone Wall',
			buildCost: {stone:8,lumber:2},
			buildTime: 28,
			replaces: ['woodenPalisade'],
			goodwill: 2,
			visible: true,
			defense:3,
		},
		tannery: {
			name:'Tannery',
			buildCost: {stone:1,lumber:1,hides:5,fiber:1},
			buildTime: 8,
			goodwill: 2,
			visible: false,
			inputs: ['hides'],
			outputs: ['leather'],
			jobs: 6,
		},
		tenements: {
			name:'Tenements',
			buildCost: {stone:8,lumber:4,cloth:2,furniture:2},
			buildTime: 42,
			replaces: ['hovels'],
			goodwill: 5,
			visible: true,
			inputs: ['fuel','clothing','furniture'],
			housing:200,
			jobs: 10,
		},
		warehouse: {
			name: 'Warehouse',
			buildCost: {stone:2,lumber:4},
			buildTime: 14,
			goodwill: -3,
			visible: false,
			jobs: 5,
			warehousing: true,
			initial: 'W',
		},
		watchtower: {
			name:'Watchtower',
			buildCost: {lumber:4,fiber:2},
			buildTime: 6,
			goodwill: 1,
			visible: true,
			defense:1,
		},
		watermill: {
			name: 'Watermill',
			buildCost: {lumber:4,stone:1,cloth:2},
			requiredResource: ['river'],
			buildTime: 28,
			goodwill:5,
			visible: false,
			outputs: ['food'],
			jobs: 8,
		},
		well: {
			name: 'Well',
			buildCost: {stone:2,lumber:1},
			requiredResource: ['spring'],
			buildTime: 4,
			goodwill:1,
			visible: false,
			outputs: ['water'],
		},
		woodenPalisade: {
			name:'Wooden Palisade',
			buildCost: {lumber:4,fiber:2},
			buildTime: 6,
			goodwill: 1,
			visible: true,
			defense:2,
		},
	},
	
	resources: {
	
		forest: {
			name: "Forest",
			visible: true,
			suffices: [' Wood','wood',' Glen','dale'],
			description: "A nearby wood full of lumberable trees and huntable game.",
		},
		mineralVein: {
			name: "Mineral Vein",
			visible: false,
			description: "A vein of minerals that can be mined.",
		},
		oilReservoir: {
			name: "Oil Reservoir",
			visible: false,
			description: "A vast underground reservoir of crude oil that can be pumped to the surface.",
		},
		outcropping: {
			name: "Outcropping",
			visible: true,
			suffices: [' Rock',' Spire'],
			description: "A great tower of useful stone that can be quarried.",
		},
		pasture: {
			name: "Pasture",
			visible: false,
			description: "Broad expanses of verdant land suitable for raising livestock.",
		},
		spring: {
			name: "Spring",
			visible: false,
			description: "An underground river or stream bubbles up here, providing a source of water for the community.",
		},
		river: {
			name: "River",
			visible: true,
			suffices: [' River',' Creek',' Port','side','bank'],
			description: "This town has access to a running river, providing a source of water as well as fish.  The power of the river can also be tapped with a watermill.",
		},
		ruins: {
			name: "Old World Ruin",
			visible: false,
			suffices: [' Pile'],
			description: "An all but forgotten ruin of an Old World structure.  There may be useful materials inside, and the bones of the structure might still prove habitable.",
		},
	
	},
	
	units: {
	
		donkeyCart: {
			name: 'Donkey Cart',
			symbol: 'donkeyCart',
			cargo: 4,
			crew: 2,
			fuel: {water:1},
			speed: 10,
			offroadSpeed: 5,
			buildCost: {lumber:2,fiber:2,tack:1,food:1,water:1},
		},
	
		horseCart: {
			name: 'Horse Cart',
			symbol: 'horseCart',
			cargo: 5,
			crew: 2,
			fuel: {water:3},
			speed: 15,
			offroadSpeed: 5,
			buildCost: {lumber:3,fiber:3,tack:1,food:1,water:1},
		},
	
		oxCart: {
			name: 'Ox Cart',
			symbol: 'oxCart',
			cargo: 5,
			crew: 2,
			fuel: {water:3},
			speed: 10,
			offroadSpeed: 8,
			buildCost: {lumber:3,fiber:3,tack:1,food:1,water:1},
		},
	
		tinkersCart: {
			name: "Tinker's Cart",
			symbol: 'tinkersCart',
			unlockable: true,
			cargo: 5,
			crew: 3,
			fuel: {water:2},
			speed: 10,
			offroadSpeed: 7,
			canBuild: true,
			buildInfrastructures: [
				'barracks',
				'bunker',
				'carpenter',
				'cisterns',
				'corral',
				'fields',
				'granary',
				'loom',
				'lumbermill',
				'openPitMine',
				'orchards',
// 				'postOffice',
				'rowhouses',
				'saddler',
				'scrapyard',
				'seamstress',
				'seine',
				'shantyTown',
				'tannery',
				'well',
				'watchtower',
				'watermill',
				'warehouse',
				'woodenPalisade'
			],
			buildCost: {lumber:4,fiber:4,tack:1,stone:1,food:1,water:1},
		},
	
		constructionCrew: {
			name: "Construction Crew",
			symbol: 'constructionCrew',
			cargo: 6,
			crew: 5,
			fuel: {fuel:2},
			speed: 10,
			offroadSpeed: 3,
			canBuild: true,
			buildInfrastructures: [
				'aqueduct',
				'barracks',
				'bunker',
				'canals',
				'carpenter',
				'cisterns',
				'fields',
				'fireStation',
				'fortress',
				'foundry',
				'loom',
				'lumbermill',
				'manorHouse',
				'mineshaft',
				'oilWell',
				'orchards',
// 				'postOffice',
				'quarry',
				'refinery',
				'reservoir',
				'rowhouses',
				'saddler',
				'seamstress',
				'stoneWall',
				'tannery',
				'tenements',
				'warehouse',
				'watermill'
			],
			buildCost: {metals:6,fuel:6,cloth:4,food:1,water:1},
		},
	
		dowser: {
			name: "Dowser",
			symbol: 'dowser',
			unlockable: true,
			cargo: 2,
			crew: 1,
			fuel: {water:1},
			speed: 8,
			offroadSpeed: 2,
			canSurvey: true,
			surveyTime: 14,
			surveyResources: ['mineralVein','oilReservoir','pasture','ruins','spring'],
			buildCost: {lumber:2,fiber:2,stone:1,tack:1,food:1,fuel:2,water:1},
		},
		
		outriders: {
			name: 'Outriders',
			symbol: 'outriders',
			unlockable: true,
			cargo: 0,
			crew: 2,
			fuel: {water:1},
			speed: 14,
			offroadSpeed: 14,
			buildCost: {tack:1,water:1,food:1},
		},
		
		bicycle: {
			name: 'Bicycle',
			symbol: 'bicycle',
			unlockable: true,
			cargo: 1,
			crew: 1,
			fuel: {},
			speed: 8,
			offroadSpeed: 5,
			buildCost: {metals:1,food:1},
		},
		
		buggy: {
			name: 'Buggy',
			symbol: 'buggy',
			cargo: 3,
			crew: 1,
			fuel: {fuel:1},
			speed: 20,
			offroadSpeed: 20,
			buildCost: {metals:3,fuel:1,food:1},
		},
		
		wagon: {
			name: 'Station Wagon',
			symbol: 'wagon',
			cargo: 5,
			crew: 2,
			fuel: {fuel:1},
			speed: 20,
			offroadSpeed: 10,
			buildCost: {metals:4,fuel:2,food:1},
			canPassenger: true,
		},
		
		truck: {
			name: 'Truck',
			symbol: 'truck',
			cargo: 6,
			crew: 2,
			fuel: {fuel:2},
			speed: 25,
			offroadSpeed: 12,
			buildCost: {metals:4,fuel:2,food:1},
		},
		
		bus: {
			name: 'Bus',
			symbol: 'bus',
			unlockable: true,
			cargo: 10,
			crew: 2,
			fuel: {fuel:2},
			speed: 25,
			offroadSpeed: 5,
			buildCost: {metals:8,fuel:2,food:1},
			canPassenger: true,
		},
		
		semi: {
			name: 'Semi',
			symbol: 'semi',
			cargo: 15,
			crew: 4,
			fuel: {fuel:3},
			speed: 20,
			offroadSpeed: 5,
			buildCost: {metals:8,fuel:2,food:1},
		},
		
		escort: {
			name: 'Escort Motorbikes',
			symbol: 'escort',
			unlockable: true,
			cargo: 0,
			crew: 2,
			fuel: {fuel:1},
			speed: 30,
			offroadSpeed: 20,
			buildCost: {metals:2,fuel:1,food:1},
		},
		
		zeppelin: {
			name: 'Zeppelin',
			symbol: 'zeppelin',
			cargo: 10,
			crew: 4,
			fuel: {fuel:3},
			speed: 0,
			offroadSpeed: 20,
			buildCost: {metals:5,cloth:20,fiber:5,food:1,fuel:1},
			canPassenger: true,
			airborne: true,
		},
	
	},

};